services:
  app:
    image: ghcr.io/allpynn/web-monitoring-tahfidz:latest
    container_name: laravel_app_dev
    restart: always
    env_file:
      - .env
    environment:
      DB_DATABASE: tahfidz_db
    volumes:
      - .:/var/www
    ports:
      - "8081:8000"
    command: php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --watch

  reverb:
    image: ghcr.io/allpynn/web-monitoring-tahfidz:latest
    container_name: laravel_reverb_dev
    restart: always
    env_file:
      - .env
    environment:
      DB_DATABASE: tahfidz_db
    volumes:
      - .:/var/www
    ports:
      - "8082:8080"
    command: php artisan reverb:start --host=0.0.0.0 --port=8080

  queue:
    image: ghcr.io/allpynn/web-monitoring-tahfidz:latest
    container_name: laravel_queue_dev
    restart: always
    env_file:
      - .env
    environment:
      DB_DATABASE: tahfidz_db
    volumes:
      - .:/var/www
    command: php artisan queue:work --sleep=3 --tries=3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_dev
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 300M
    ports:
      - "8083:80"
